services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: